import { createElement } from 'lwc';
import EnergyMW_11_03_23_Chart from 'c/energyMW_11_03_23_Chart';

describe('c-energy-m-w-11-03-23-chart', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-energy-m-w-11-03-23-chart', {
            is: EnergyMW_11_03_23_Chart
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});