import { createElement } from 'lwc';
import EnergyOutput_11_03_23 from 'c/energyOutput_11_03_23';

describe('c-energy-output-11-03-23', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-energy-output-11-03-23', {
            is: EnergyOutput_11_03_23
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});